### ISSUE TITLE
IIR windowing

### ISSUE THREAD

**Issue by TF3RDL** [jurihock/qdft#3]
It is worth noting that asymmetric window functions are impossible to implement, not even the window skew parameter outlined in [my collection of audio analysis functions](https://gist.github.com/TF3RDL/15326358806cabe3d69be792ff0012c7#file-audio-analyzer-js-L143) on a sliding DFT, but what you can do is make the sDFT an IIR filter bank (which is a damped sine wave). which uses less RAM (since it doesn't need ring buffers) and it can be cascaded (just like biquad filters) to achieve a steeper rolloff at the cost of greater delay (thus, bad time resolution) on long window sizes

**Comment by jurihock** [comment]
Thanks for suggestion!

As always, the are many ways to do something. The current implementation aims not to be the most "perfect" one. But it's good enough to start with, I think.

And yes, I'm not that happy about the input buffering. Not much because of the footprint or linear access to it, but because of the circular shift, required for the each input sample. I still decided to use std::rotate for more transparency instead of branching or cursor adjustments in the loop.

I'm not sure about the efficiency/stability of an IIR filter bank. Since the output latency is more important to me, it's not a compromise. But anyway I'll think about it again when I get a chance...

**Comment by jurihock** [comment]
Closing, as std::rotate issue is fixed in #4.

**Comment by jurihock** [comment]
Further reading:

- [The Sliding Windowed Infinite Fourier Transform](https://ieeexplore.ieee.org/document/8026592)
- [Digital signal processing using sliding windowed infinite fourier transform](https://patents.google.com/patent/US20180365194A1)
